// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgnnrtYggMsB8GEpurR4Nv4f_rjtdczX0',
    appId: '1:450570137274:web:0487b10199f7d7606f1c83',
    messagingSenderId: '450570137274',
    projectId: 'knight4love2',
    authDomain: 'knight4love2.firebaseapp.com',
    storageBucket: 'knight4love2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hC5hSJQxrOBf9kjCr_AJjw4s8SWXorY',
    appId: '1:450570137274:android:9b17ec3a77a7d9256f1c83',
    messagingSenderId: '450570137274',
    projectId: 'knight4love2',
    storageBucket: 'knight4love2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoQRqZnLfR-SSY7uYVMxrHutUq-ii8jQ',
    appId: '1:450570137274:ios:02fbcc23990840ed6f1c83',
    messagingSenderId: '450570137274',
    projectId: 'knight4love2',
    storageBucket: 'knight4love2.appspot.com',
    iosClientId: '450570137274-r2tffqgoceq762og6k060aqv36lri8kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.knights4love2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoQRqZnLfR-SSY7uYVMxrHutUq-ii8jQ',
    appId: '1:450570137274:ios:02fbcc23990840ed6f1c83',
    messagingSenderId: '450570137274',
    projectId: 'knight4love2',
    storageBucket: 'knight4love2.appspot.com',
    iosClientId: '450570137274-r2tffqgoceq762og6k060aqv36lri8kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.knights4love2',
  );
}
